cache:
  paths:
  - vendor/

before_script:
- apt-get update -yqq
- apt-get install -yqq git unzip zlib1g-dev
- docker-php-ext-install zip
- pecl install xdebug
- docker-php-ext-enable xdebug
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install

test:7.4:
  image: php:7.4
  script:
  - vendor/bin/phpunit --coverage-text --colors=never

test:8.0:
  image: php:8.0
  script:
  - vendor/bin/phpunit --coverage-text --colors=never

test:8.1:
  image: php:8.1
  script:
  - vendor/bin/phpunit --coverage-text --colors=never